"use strict";
const test=require("node:test"); const assert=require("node:assert/strict"); const fs=require("node:fs"); const os=require("node:os"); const path=require("node:path");
const {buildPlan,installPlan,validateRequest,PROTOCOL_VERSION}=require("./installer-adapter.js");
function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),"installer-v2-"));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));fs.mkdirSync(path.join(root,"agents"));fs.writeFileSync(path.join(root,"agents","alpha.agent.md"),"---\nname: alpha\n---\n");fs.writeFileSync(path.join(root,"models.yaml"),`agents:\n  alpha: default\n  _default: default\ninstaller:\n  phase_groups:\n    phases:\n      label: Phases\n      agents: [alpha]\n  presets:\n    recommended:\n      label: Recommended\n      groups: [phases]\n  capabilities:\n    claude:\n      sonnet:\n        effort: { values: [low, medium, high], default: medium }\n      opus:\n        effort: { values: [low, medium, high], default: medium }\n    codex:\n      gpt:\n        model_reasoning_effort: { values: [low, medium, high, xhigh], default: high }\n    opencode:\n      open/a:\n        variant: { values: [\"\", fast], default: \"\" }\ntiers:\n  premium:\n    claude: opus\n    vscode: [copilot]\n    github-copilot: [copilot]\n    codex:\n      model: gpt\n      model_reasoning_effort: high\n    opencode: open/a\n    cursor: cursor\n  default:\n    claude: sonnet\n    vscode: [copilot]\n    github-copilot: [copilot]\n    codex:\n      model: gpt\n      model_reasoning_effort: high\n    opencode: open/a\n    cursor: cursor\n  cheap:\n    claude: haiku\n    vscode: [copilot]\n    github-copilot: [copilot]\n    codex:\n      model: gpt\n      model_reasoning_effort: low\n    opencode: open/a\n    cursor: cursor\ncatalog:\n  claude: [opus, sonnet]\n  vscode: [copilot]\n  github-copilot: [copilot]\n`);return root}
function target(plan,id){return plan.targets.find(x=>x.id===id)}
function presetRequest(plan,id){const t=target(plan,id),p=t.presets[0];return {version:PROTOCOL_VERSION,target:id,mode:"preset",presetId:p.id,selections:p.selections}}
test("v2 plan is static, scopes opaque IDs by target and preserves Antigravity inheritance",t=>{const root=fixture(t),before=fs.readFileSync(path.join(root,"models.yaml"),"utf8"),plan=buildPlan({sourceDir:root});assert.equal(plan.version,2);assert.deepEqual(target(plan,"vscode").agents[0].choices.map(x=>x.label),target(plan,"github-copilot").agents[0].choices.map(x=>x.label));assert.notDeepEqual(target(plan,"vscode").agents[0].choices.map(x=>x.id),target(plan,"github-copilot").agents[0].choices.map(x=>x.id));assert.equal(target(plan,"antigravity").inherited,true);assert.deepEqual(target(plan,"antigravity").presets,[]);assert.equal(fs.readFileSync(path.join(root,"models.yaml"),"utf8"),before)})
test("fresh v2 validation rejects forged IDs and delegates exactly once",t=>{const root=fixture(t),plan=buildPlan({sourceDir:root}),request=presetRequest(plan,"claude");assert.throws(()=>validateRequest({...request,selections:{alpha:{choiceId:"forged"}}},plan),/fresh plan/);let calls=0;assert.equal(installPlan(request,{sourceDir:root,mains:{claude:(_argv,deps)=>{calls++;const options=deps.runConfigure({target:"claude"});assert.equal(options.modelOverrides.alpha,"sonnet");return 0}},runConfigure:x=>x}),0);assert.equal(calls,1)})
test("controls are finite and unsupported metadata fails closed",t=>{const root=fixture(t),plan=buildPlan({sourceDir:root}),request=presetRequest(plan,"codex");request.mode="custom";delete request.presetId;request.selections.alpha.controls={model_reasoning_effort:"xhigh"};assert.doesNotThrow(()=>validateRequest(request,plan));request.selections.alpha.controls={variant:"fast"};assert.throws(()=>validateRequest(request,plan),/unsupported control/)})
