"use strict";

// Private v2 boundary for the Go installer. The plan is a read-only snapshot;
// installation rebuilds it and validates opaque IDs before one delegation.
const fs = require("node:fs");
const path = require("node:path");
const { PROFILES, parseModels, runConfigure: configure } = require("./cli.js");
const { canonicalControlsFor, validateInstallerPolicy } = require("../lib/model-resolver.js");
const PROTOCOL_VERSION = 2;
const TARGET_INFO = { claude: ["Claude", "Install the Claude marketplace plugin"], vscode: ["VS Code", "Install VS Code settings and prompts"], "github-copilot": ["GitHub Copilot", "Install GitHub Copilot configuration"], opencode: ["OpenCode", "Install OpenCode configuration"], codex: ["Codex", "Install Codex configuration"], cursor: ["Cursor", "Install Cursor configuration"], antigravity: ["Antigravity", "Install Antigravity configuration"] };
const SELECTABLE = new Set(["claude", "vscode", "github-copilot", "opencode", "codex", "cursor"]);
const CONTROL_BY_TARGET = { claude: "effort", codex: "model_reasoning_effort", opencode: "variant" };

function stableJson(value) { if (Array.isArray(value)) return `[${value.map(stableJson).join(",")}]`; if (value && typeof value === "object") return `{${Object.keys(value).sort().map(key => `${JSON.stringify(key)}:${stableJson(value[key])}`).join(",")}}`; return JSON.stringify(value); }
function clone(value) { return JSON.parse(stableJson(value)); }
function choiceId(target, value) { return Buffer.from(stableJson({ target, value })).toString("base64url"); }
function same(a, b) { return stableJson(a) === stableJson(b); }
function isValue(value) { return value !== undefined && value !== null && value !== "inherit"; }
function requestError(message) { const err = new Error(`invalid install request: ${message}`); err.exitCode = 2; return err; }
function readModels(sourceDir) { const models = parseModels(fs.readFileSync(path.join(sourceDir, "models.yaml"), "utf8")); const policy = validateInstallerPolicy(models); if (!policy.valid) throw requestError(`invalid models policy: ${JSON.stringify(policy.errors)}`); return models; }
function readAgents(sourceDir) { return fs.readdirSync(path.join(sourceDir, "agents"), { withFileTypes: true }).filter(entry => entry.isFile() && entry.name.endsWith(".agent.md")).map(entry => entry.name.slice(0, -".agent.md".length)).sort(); }
function agentValue(models, id, target) { const tier = models.agents?.[id] ?? models.agents?._default; return models.tiers?.[tier]?.[target]; }
function catalogValues(models, target, effective) { const values = []; for (const tier of Object.values(models.tiers || {})) if (isValue(tier?.[target])) values.push(tier[target]); const catalog = models.catalog?.[target]; if (Array.isArray(catalog)) values.push(...catalog); else if (catalog && typeof catalog === "object") values.push(...Object.values(catalog)); if (isValue(effective)) values.push(effective); return values.filter(isValue).filter((value, index, all) => all.findIndex(other => same(other, value)) === index); }
function nativeModel(value) { return value && typeof value === "object" && !Array.isArray(value) ? value.model : value; }
function label(value) { return Array.isArray(value) ? value.join(", ") : String(nativeModel(value) || value); }
function controlsFor(models, target, value) { return canonicalControlsFor(models, target, value); }
function makeAgent(models, target, id) { const effective = agentValue(models, id, target); const selectable = SELECTABLE.has(target) && isValue(effective); const choices = selectable ? catalogValues(models, target, effective).map(value => ({ id: choiceId(target, value), label: label(value), value: clone(value), controls: controlsFor(models, target, value) })) : []; return { id, selectable, inherited: !selectable, effective: selectable ? clone(effective) : null, choices }; }
function makePresets(models, target) { if (target.inherited) return []; const selections = Object.fromEntries(target.agents.filter(agent => agent.selectable).map(agent => [agent.id, { choiceId: agent.choices.find(choice => same(choice.value, agent.effective))?.id, controls: {} }])); return Object.entries(models.installer.presets).map(([id, preset]) => ({ id, label: preset?.label || id, selections })); }
function makeGroups(models) { return Object.entries(models.installer.phase_groups).map(([id, group]) => ({ id, label: group?.label || id, agents: group.agents })); }
function buildPlan({ sourceDir = process.cwd() } = {}) { const models = readModels(sourceDir), ids = readAgents(sourceDir); return { version: PROTOCOL_VERSION, targets: Object.keys(PROFILES).map(id => { const [label, installDescription] = TARGET_INFO[id] || [id, `Install ${id}`]; const target = { id, label, installDescription, inherited: id === "antigravity", agents: ids.map(agent => makeAgent(models, id, agent)), groups: makeGroups(models), presets: [] }; target.presets = makePresets(models, target); return target; }) }; }
function applyControls(value, controls) { if (!Object.keys(controls).length) return value; return value && typeof value === "object" && !Array.isArray(value) ? { ...value, ...controls } : { model: value, ...controls }; }
function validateSelection(agent, selection) { if (!selection || typeof selection !== "object" || Array.isArray(selection) || typeof selection.choiceId !== "string" || Object.keys(selection).some(key => key !== "choiceId" && key !== "controls")) throw requestError(`invalid selection for ${agent.id}`); const choice = agent.choices.find(item => item.id === selection.choiceId); if (!choice) throw requestError(`unknown choice for ${agent.id}`); const controls = selection.controls === undefined ? {} : selection.controls; if (!controls || typeof controls !== "object" || Array.isArray(controls)) throw requestError(`invalid controls for ${agent.id}`); for (const [name, value] of Object.entries(controls)) { const policy = choice.controls?.[name]; if (!policy || !policy.values.includes(value)) throw requestError(`unsupported control ${name} for ${agent.id}`); } return applyControls(clone(choice.value), controls); }
function validateRequest(request, plan) { if (!request || typeof request !== "object" || Array.isArray(request)) throw requestError("must be an object"); const allowed = ["version", "target", "mode", "presetId", "selections"]; if (Object.keys(request).some(key => !allowed.includes(key)) || request.version !== PROTOCOL_VERSION || typeof request.target !== "string" || !["preset", "custom", "inherited"].includes(request.mode) || !request.selections || typeof request.selections !== "object" || Array.isArray(request.selections)) throw requestError("has an invalid schema"); const target = plan.targets.find(item => item.id === request.target); if (!target) throw requestError("unknown target"); if (target.inherited) { if (request.mode !== "inherited" || request.presetId !== undefined || Object.keys(request.selections).length) throw requestError("inherited target requires empty selections"); return { target: target.id, modelOverrides: {} }; } const agents = target.agents.filter(agent => agent.selectable); const required = agents.map(agent => agent.id).sort(), names = Object.keys(request.selections).sort(); if (names.length !== required.length || names.some((name, index) => name !== required[index])) throw requestError("missing, unknown, or inherited selection"); if (request.mode === "preset") { const preset = target.presets.find(item => item.id === request.presetId); if (!preset || !same(preset.selections, request.selections)) throw requestError("preset selections do not match the fresh plan"); } else if (request.presetId !== undefined) throw requestError("custom request cannot include presetId"); return { target: target.id, modelOverrides: Object.fromEntries(agents.map(agent => [agent.id, validateSelection(agent, request.selections[agent.id])])) }; }
function defaultMain(target) { return require({ claude: "./install-claude.js", vscode: "./install-vscode.js", "github-copilot": "./install-global-copilot.js", opencode: "./install-global-opencode.js", codex: "./install-codex.js", cursor: "./install-cursor.js", antigravity: "./install-antigravity.js" }[target]).main; }
function installPlan(request, { sourceDir = process.cwd(), mains = {}, runConfigure: runConfigureImpl = configure } = {}) { const { target, modelOverrides } = validateRequest(request, buildPlan({ sourceDir })); const installer = mains[target] || defaultMain(target); const result = installer([], { cwd: sourceDir, runConfigure: options => runConfigureImpl({ ...options, sourceDir, modelOverrides }) }); if (result && typeof result.then === "function") throw requestError("installer must complete synchronously"); if (!Number.isInteger(result) || result < 0) throw requestError("installer must return a non-negative integer exit code"); return result; }
function main(argv = process.argv.slice(2), deps = {}) { const stdout = deps.stdout || process.stdout, stderr = deps.stderr || process.stderr, sourceDir = deps.sourceDir || process.cwd(); if (argv.length === 1 && argv[0] === "plan") { try { stdout.write(`${JSON.stringify(buildPlan({ sourceDir }))}\n`); return 0; } catch (err) { stderr.write(`${err.message}\n`); return 2; } } if (argv.length !== 1 || argv[0] !== "install") { stderr.write("usage: installer-adapter <plan|install>\n"); return 2; } try { return installPlan(JSON.parse(deps.stdin === undefined ? fs.readFileSync(0, "utf8") : String(deps.stdin)), { ...deps, sourceDir }); } catch (err) { stderr.write(`${err.message || err}\n`); return err.exitCode || 2; } }
if (require.main === module) process.exitCode = main();
module.exports = { PROTOCOL_VERSION, buildPlan, installPlan, main, stableJson, validateRequest };
