// Generated by scripts/configure — do not edit by hand.
// Bridges the SDD runtime (scripts/hooks/*.js) into opencode plugin events,
// because opencode has no shell-command hooks. See the generator's
// scripts/lib/target-profiles/opencode-plugin.js for rationale.
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const require = createRequire(import.meta.url);
const here = dirname(fileURLToPath(import.meta.url));
const { evaluateToolUse } = require(join(here, "../../scripts/hooks/pre-tool-use.js"));
const { runSessionStart } = require(join(here, "../../scripts/hooks/session-start.js"));

export const OspecWorkflowPlugin = async ({ directory }) => {
  return {
    event: async ({ event }) => {
      if (event && event.type === "session.created") {
        try {
          await runSessionStart({ input: { cwd: directory } });
        } catch {
          // session-start is best-effort; never block a session on cache build.
        }
      }
    },
    "tool.execute.before": async (input, output) => {
      const decision = evaluateToolUse({
        tool_name: input && input.tool,
        tool_input: (output && output.args) || {},
      });
      const verdict = decision && decision.hookSpecificOutput;
      if (!verdict) {
        return;
      }
      // opencode plugins can only allow (return) or block (throw) — no native ask.
      if (verdict.permissionDecision === "deny") {
        throw new Error(verdict.permissionDecisionReason);
      }
      if (verdict.permissionDecision === "ask") {
        throw new Error("Requires approval: " + verdict.permissionDecisionReason);
      }
    },
  };
};
