// Generated by scripts/configure — do not edit by hand.
// Bridges the SDD runtime Go binary (ospec-hooks) into opencode plugin events,
// because opencode has no shell-command hooks. See the generator's
// scripts/lib/target-profiles/opencode-plugin.js for rationale.
import { spawnSync } from "node:child_process";
import { existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const isWin = process.platform === "win32";
const EXE = isWin ? ".exe" : "";

export function resolveBinary({ here: pluginDir = here, extension = EXE, exists = existsSync } = {}) {
  // Global plugins live at ~/.config/opencode/plugins; project plugins use .opencode/plugins.
  const globalDistBin = resolve(join(pluginDir, "..", "release", "dist", "ospec-hooks" + extension));
  if (exists(globalDistBin)) {
    return globalDistBin;
  }
  const localDistBin = resolve(join(pluginDir, "..", "..", "release", "dist", "ospec-hooks" + extension));
  if (exists(localDistBin)) {
    return localDistBin;
  }
  // PATH is a developer fallback, never the managed installation source.
  return "ospec-hooks" + extension;
}

export const OspecWorkflowPlugin = async ({ directory }) => {
  return {
    event: async ({ event }) => {
      if (event && event.type === "session.created") {
        try {
          const bin = resolveBinary();
          spawnSync(bin, ["session-start"], {
            input: JSON.stringify({ cwd: directory }),
            encoding: "utf8",
            shell: false,
          });
        } catch {
          // session-start is best-effort; never block a session on cache build.
        }
      }
    },
    "tool.execute.before": async (input, output) => {
      const bin = resolveBinary();
      const result = spawnSync(bin, ["pre-tool-use"], {
        input: JSON.stringify({
          tool_name: input && input.tool,
          tool_input: (output && output.args) || {},
        }),
        encoding: "utf8",
        shell: false,
      });
      if (result.error) {
        throw new Error("[ospec-workflow] pre-tool-use hook failed: " + result.error.message);
      }
      if (result.status !== 0) {
        throw new Error("[ospec-workflow] pre-tool-use hook failed with status " + result.status);
      }
      let verdict = null;
      try {
        const parsed = JSON.parse(result.stdout || "{}");
        verdict = parsed && parsed.hookSpecificOutput;
      } catch (err) {
        throw new Error("[ospec-workflow] pre-tool-use invalid output: " + err.message);
      }
      if (!verdict) {
        return;
      }
      // opencode plugins can only allow (return) or block (throw) — no native ask.
      if (verdict.permissionDecision === "deny" || verdict.permissionDecision === "ask") {
        throw new Error(verdict.permissionDecisionReason || "Blocked by ospec-workflow safety policy");
      }
    },
  };
};
