// @ts-check
import { readFileSync } from "node:fs";
import { basename, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { defineConfig } from "astro/config";
import starlight from "@astrojs/starlight";
import mermaid from "astro-mermaid";

// This project is a generated Starlight shell (Option D of sdd-document).
// Content under src/content/docs/ is populated exclusively by
// scripts/sync-openwiki.mjs from ../openwiki/ — do not author pages here.

const HERE = dirname(fileURLToPath(import.meta.url));

/** "ospec-workflow" | "@org/ospec-workflow" -> "Ospec-Workflow" */
function titleCaseName(name) {
  const bare = name.includes("/") ? name.split("/").pop() : name;
  return bare
    .split("-")
    .map((seg) => (seg ? seg.charAt(0).toUpperCase() + seg.slice(1) : seg))
    .join("-");
}

// Site title: the parent repository's package.json name, falling back to the
// repository directory name, then to a generic label. Never hand-edit here —
// fix the parent package.json instead.
function resolveSiteTitle() {
  try {
    const pkg = JSON.parse(readFileSync(resolve(HERE, "..", "package.json"), "utf8"));
    if (pkg.name) return titleCaseName(pkg.name);
  } catch {
    // No parent package.json (non-Node repo): fall through to the dir name.
  }
  const dir = basename(resolve(HERE, ".."));
  return dir ? titleCaseName(dir) : "Project Documentation";
}

// Sidebar: consumes the manifest emitted by scripts/sync-openwiki.mjs at
// predev/prebuild time (quickstart first, groups in the quickstart's own
// narrative order). Falls back to Starlight's default autogenerated sidebar
// when the manifest is missing or unreadable.
function resolveSidebar() {
  try {
    const manifest = JSON.parse(
      readFileSync(resolve(HERE, "src", "sidebar.generated.json"), "utf8")
    );
    return [
      ...manifest.topLinks.map((t) => ({ label: t.label, link: t.link })),
      ...manifest.groups.map((g) => ({
        label: g.label,
        autogenerate: { directory: g.directory },
      })),
    ];
  } catch {
    return undefined;
  }
}

export default defineConfig({
  redirects: {
    "/": "/quickstart",
  },
  integrations: [
    mermaid(),
    starlight({
      title: resolveSiteTitle(),
      favicon: "/favicon.png",
      logo: {
        src: "./src/assets/ospec-logo.png",
        alt: "Ospec-Workflow",
      },
      sidebar: resolveSidebar(),
      customCss: ["./src/styles/custom.css"],
    }),
  ],
});
