// @ts-check
import { readFileSync } from "node:fs";
import { basename, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { defineConfig } from "astro/config";
import starlight from "@astrojs/starlight";
import mermaid from "astro-mermaid";

// This project is a generated Starlight shell (Option D of sdd-document).
// Content under src/content/docs/ is populated exclusively by
// scripts/sync-openwiki.mjs from ../openwiki/ — do not author pages here.

const HERE = dirname(fileURLToPath(import.meta.url));

/** "ospec-workflow" | "@org/ospec-workflow" -> "Ospec-Workflow" */
function titleCaseName(name) {
  const bare = name.includes("/") ? name.split("/").pop() : name;
  return bare
    .split("-")
    .map((seg) => (seg ? seg.charAt(0).toUpperCase() + seg.slice(1) : seg))
    .join("-");
}

// Site title: the parent repository's package.json name, falling back to the
// repository directory name, then to a generic label. Never hand-edit here —
// fix the parent package.json instead.
function resolveSiteTitle() {
  try {
    const pkg = JSON.parse(readFileSync(resolve(HERE, "..", "package.json"), "utf8"));
    if (pkg.name) return titleCaseName(pkg.name);
  } catch {
    // No parent package.json (non-Node repo): fall through to the dir name.
  }
  const dir = basename(resolve(HERE, ".."));
  return dir ? titleCaseName(dir) : "Project Documentation";
}

// Sidebar: consumes the manifest emitted by scripts/sync-openwiki.mjs at
// predev/prebuild time (quickstart first, groups in the quickstart's own
// narrative order). Falls back to Starlight's default autogenerated sidebar
// when the manifest is missing or unreadable.
function resolveSidebar() {
  try {
    const manifest = JSON.parse(
      readFileSync(resolve(HERE, "src", "sidebar.generated.json"), "utf8")
    );
    return [
      ...manifest.topLinks.map((t) => ({ label: t.label, link: t.link })),
      ...manifest.groups.map((g) => ({
        label: g.label,
        items: [{ autogenerate: { directory: g.directory } }],
      })),
    ];
  } catch {
    return undefined;
  }
}

export default defineConfig({
  site: "https://snakeblack.github.io/ospec-workflow",
  redirects: {
    "/": "/quickstart",
  },
  integrations: [
    mermaid(),
    starlight({
      title: resolveSiteTitle(),
      description:
        "Spec-Driven Development (SDD) workflow with OpenSpec, strict TDD, lifecycle hooks, and multi-target code generation.",
      favicon: "/favicon.png",
      logo: {
        src: "./src/assets/ospec-logo.png",
        alt: "Ospec-Workflow",
      },
      sidebar: resolveSidebar(),
      social: [
        {
          icon: "github",
          label: "GitHub",
          href: "https://github.com/snakeblack/ospec-workflow",
        },
      ],
      customCss: ["./src/styles/custom.css"],
      tableOfContents: {
        minHeadingLevel: 2,
        maxHeadingLevel: 4,
      },
      expressiveCode: {
        themes: ["github-dark-dimmed", "github-light"],
        styleOverrides: {
          borderRadius: "0.75rem",
          codeFontFamily:
            "'JetBrains Mono', 'Fira Code', ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
          uiFontFamily:
            "'Plus Jakarta Sans', 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
          codeFontSize: "0.875rem",
          codeLineHeight: "1.7",
        },
      },
      head: [
        {
          tag: "meta",
          attrs: {
            name: "robots",
            content:
              "index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1",
          },
        },
        {
          tag: "meta",
          attrs: {
            name: "keywords",
            content:
              "OpenSpec, SDD, Spec-Driven Development, AI Agents, TDD, Claude, Copilot, VS Code, Codex, Architecture",
          },
        },
        {
          tag: "meta",
          attrs: {
            property: "og:type",
            content: "website",
          },
        },
        {
          tag: "meta",
          attrs: {
            property: "og:site_name",
            content: "Ospec-Workflow Documentation",
          },
        },
        {
          tag: "meta",
          attrs: {
            property: "og:image",
            content: "https://snakeblack.github.io/ospec-workflow/favicon.png",
          },
        },
        {
          tag: "meta",
          attrs: {
            name: "twitter:card",
            content: "summary_large_image",
          },
        },
        {
          tag: "meta",
          attrs: {
            name: "theme-color",
            content: "#080a10",
            media: "(prefers-color-scheme: dark)",
          },
        },
        {
          tag: "meta",
          attrs: {
            name: "theme-color",
            content: "#ffffff",
            media: "(prefers-color-scheme: light)",
          },
        },
        {
          tag: "link",
          attrs: {
            rel: "preconnect",
            href: "https://fonts.googleapis.com",
          },
        },
        {
          tag: "link",
          attrs: {
            rel: "preconnect",
            href: "https://fonts.gstatic.com",
            crossorigin: "",
          },
        },
        {
          tag: "link",
          attrs: {
            rel: "stylesheet",
            href: "https://fonts.googleapis.com/css2?family=JetBrains+Mono:ital,wght@0,400;0,500;0,600;1,400&family=Plus+Jakarta+Sans:ital,wght@0,400;0,500;0,600;0,700;0,800;1,400;1,600&display=swap",
          },
        },
        {
          tag: "script",
          attrs: {
            type: "module",
            src: "/scripts/webmcp-doc-tools.js",
          },
        },
      ],
    }),
  ],
});
