"use strict";

// The opencode plugin shim, shipped verbatim at .opencode/plugins/ospec.js.
//
// opencode has NO shell-command hooks (unlike Claude's hooks.json or Copilot's
// .github/hooks/hooks.json) — its only extension surface is JS/TS plugins
// (https://opencode.ai/docs/plugins/). So the SDD runtime that Claude/Copilot
// wire through hooks.json is bridged here into opencode's plugin events:
//   - event "session.created"  -> scripts/hooks/session-start.js (skill cache)
//   - "tool.execute.before"    -> scripts/hooks/pre-tool-use.js  (safety policy)
//
// Those scripts ship in this same output tree (scripts/hooks + scripts/lib, via
// the generator's runtime-script gathering) and export their core functions, so
// the plugin calls them in-process instead of spawning a child node.
//
// Verified plugin API facts (opencode.ai/docs/plugins):
//   - tool.execute.before(input, output): input.tool is the tool name, output.args
//     the (mutable) arguments. A plugin BLOCKS a call by THROWING; there is no
//     native "ask". Our 3-way allow/ask/deny therefore collapses to allow (return)
//     vs. block (throw) — both deny and ask become a hard block carrying the reason,
//     so dangerous/sensitive commands are still stopped.
//   - event({ event }): fires for lifecycle events; event.type === "session.created"
//     is the session-start trigger.

const PLUGIN_SOURCE = `// Generated by scripts/configure — do not edit by hand.
// Bridges the SDD runtime (scripts/hooks/*.js) into opencode plugin events,
// because opencode has no shell-command hooks. See the generator's
// scripts/lib/target-profiles/opencode-plugin.js for rationale.
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const require = createRequire(import.meta.url);
const here = dirname(fileURLToPath(import.meta.url));
const { evaluateToolUse } = require(join(here, "../../scripts/hooks/pre-tool-use.js"));
const { runSessionStart } = require(join(here, "../../scripts/hooks/session-start.js"));

export const OspecWorkflowPlugin = async ({ directory }) => {
  return {
    event: async ({ event }) => {
      if (event && event.type === "session.created") {
        try {
          await runSessionStart({ input: { cwd: directory } });
        } catch {
          // session-start is best-effort; never block a session on cache build.
        }
      }
    },
    "tool.execute.before": async (input, output) => {
      const decision = evaluateToolUse({
        tool_name: input && input.tool,
        tool_input: (output && output.args) || {},
      });
      const verdict = decision && decision.hookSpecificOutput;
      if (!verdict) {
        return;
      }
      // opencode plugins can only allow (return) or block (throw) — no native ask.
      if (verdict.permissionDecision === "deny") {
        throw new Error(verdict.permissionDecisionReason);
      }
      if (verdict.permissionDecision === "ask") {
        throw new Error("Requires approval: " + verdict.permissionDecisionReason);
      }
    },
  };
};
`;

module.exports = { PLUGIN_SOURCE };
