"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const test = require("node:test");

const {
  FORBIDDEN_ATTRIBUTION_RE,
  findAttribution,
  runCommitMsg,
} = require("./commit-msg-hook.js");

// --- Unit tests for findAttribution ---

test("findAttribution returns null for clean conventional commits", () => {
  const messages = [
    "feat: add new feature",
    "fix(core): correct parsing\n\nDetailed explanation of the fix.",
    "docs: update README with installation steps",
    "release: v2.4.7 - Token Budget, AgentShield, and Git Pre-commit Hooks",
    "refactor: extract helper for session handling\n\nSplits large function into composable helpers.\nNo behaviour change.",
  ];

  for (const msg of messages) {
    assert.equal(findAttribution(msg), null, msg);
  }
});

test("findAttribution detects Co-Authored-By trailers", () => {
  const messages = [
    "feat: add feature\n\nCo-Authored-By: Claude Opus 4.8 <noreply@anthropic.com>",
    "fix: fix bug\n\nco-authored-by: GPT-4 <noreply@openai.com>",
    "docs: update\n\nCO-AUTHORED-BY: Gemini <noreply@google.com>",
  ];

  for (const msg of messages) {
    assert.notEqual(findAttribution(msg), null, msg);
  }
});

test("findAttribution detects model names in any line", () => {
  const lines = [
    "Generated with Claude Code",
    "Generated by GPT-4",
    "Written by Copilot",
    "🤖 Generated by claude-code",
    "Co-authored with Anthropic tools",
    "Created by Gemini",
    "Assisted by Mistral",
    "Used Llama for implementation",
    "ChatGPT assisted change",
    "Bard generated this commit",
    "Cohere model output",
    "OpenAI Codex generated",
  ];

  for (const line of lines) {
    assert.notEqual(findAttribution(line), null, line);
  }
});

test("findAttribution ignores model names in legitimate code context when they are not attribution", () => {
  // These are edge cases - the regex is intentionally broad.
  // Legitimate mentions like "fix copilot integration" WILL trigger the check.
  // This is by design: the rule says "any mention" is forbidden in commit messages.
  const attributionLines = [
    "fix: copilot integration broken",
    "docs: add claude setup guide",
  ];

  for (const line of attributionLines) {
    // These DO match because the rule forbids ANY mention of model names in commits
    assert.notEqual(findAttribution(line), null, line);
  }
});

test("FORBIDDEN_ATTRIBUTION_RE matches case-insensitively", () => {
  assert.ok(FORBIDDEN_ATTRIBUTION_RE.test("CO-AUTHORED-BY: someone"));
  assert.ok(FORBIDDEN_ATTRIBUTION_RE.test("co-authored-by: someone"));
  assert.ok(FORBIDDEN_ATTRIBUTION_RE.test("Co-Authored-By: someone"));
  assert.ok(FORBIDDEN_ATTRIBUTION_RE.test("CLAUDE"));
  assert.ok(FORBIDDEN_ATTRIBUTION_RE.test("claude"));
  assert.ok(FORBIDDEN_ATTRIBUTION_RE.test("Claude"));
});

test("FORBIDDEN_ATTRIBUTION_RE does not fire on ordinary words that merely contain a vendor name", () => {
  const cleanLines = [
    "feat: menú lateral coherente en el template", // "coherente" contains "cohere"
    "docs: mejora la coherencia del wiki",
    "fix: evita el bombardeo de warnings", // "bombardeo" contains "bard"
    "feat: muestra cómo se llaman los grupos", // "llaman" contains "llama"
  ];

  for (const line of cleanLines) {
    assert.ok(!FORBIDDEN_ATTRIBUTION_RE.test(line), line);
  }
});

test("FORBIDDEN_ATTRIBUTION_RE still fires on standalone vendor names at word boundaries", () => {
  const attributionLines = [
    "Generated with Cohere",
    "thanks to bard for the draft",
    "Written by GPT-4",
    "Used Llama for implementation",
    "cohere",
  ];

  for (const line of attributionLines) {
    assert.ok(FORBIDDEN_ATTRIBUTION_RE.test(line), line);
  }
});

// --- Integration tests for runCommitMsg ---

test("runCommitMsg exits 0 for a clean commit message", (t) => {
  let exitCode = null;
  t.mock.method(process, "exit", (code) => {
    exitCode = code;
  });

  const tmpFile = path.join(process.cwd(), "tmp_commit_msg_clean.txt");
  fs.writeFileSync(tmpFile, "feat: add cool feature\n\nDetailed description.", "utf8");
  try {
    runCommitMsg(tmpFile);
    assert.equal(exitCode, 0);
  } finally {
    fs.unlinkSync(tmpFile);
  }
});

test("runCommitMsg exits 1 for a commit message with Co-Authored-By", (t) => {
  let exitCode = null;
  t.mock.method(process, "exit", (code) => {
    exitCode = code;
  });

  const tmpFile = path.join(process.cwd(), "tmp_commit_msg_bad.txt");
  fs.writeFileSync(
    tmpFile,
    "release: bump version to 2.4.6\n\nCo-Authored-By: Claude Opus 4.8 <noreply@anthropic.com>",
    "utf8",
  );
  try {
    runCommitMsg(tmpFile);
    assert.equal(exitCode, 1);
  } finally {
    fs.unlinkSync(tmpFile);
  }
});

test("runCommitMsg exits 1 for a commit message with model name", (t) => {
  let exitCode = null;
  t.mock.method(process, "exit", (code) => {
    exitCode = code;
  });

  const tmpFile = path.join(process.cwd(), "tmp_commit_msg_model.txt");
  fs.writeFileSync(tmpFile, "feat: add feature\n\nGenerated with Claude Code", "utf8");
  try {
    runCommitMsg(tmpFile);
    assert.equal(exitCode, 1);
  } finally {
    fs.unlinkSync(tmpFile);
  }
});

test("runCommitMsg respects DISABLE_OSPEC_ATTRIBUTION_CHECK bypass", (t) => {
  let exitCode = null;
  t.mock.method(process, "exit", (code) => {
    exitCode = code;
  });

  const oldEnv = process.env.DISABLE_OSPEC_ATTRIBUTION_CHECK;
  process.env.DISABLE_OSPEC_ATTRIBUTION_CHECK = "true";

  try {
    // Even with a bad message, bypass lets it through
    runCommitMsg("nonexistent_file.txt");
    assert.equal(exitCode, 0);
  } finally {
    if (oldEnv === undefined) {
      delete process.env.DISABLE_OSPEC_ATTRIBUTION_CHECK;
    } else {
      process.env.DISABLE_OSPEC_ATTRIBUTION_CHECK = oldEnv;
    }
  }
});

test("runCommitMsg exits 0 when message file cannot be read (non-blocking)", (t) => {
  let exitCode = null;
  t.mock.method(process, "exit", (code) => {
    exitCode = code;
  });

  runCommitMsg("this_file_does_not_exist_at_all.txt");
  assert.equal(exitCode, 0);
});

// strict TDD validation comment


// ---------------------------------------------------------------------------
// B3 — Traceability trailers (Ospec-Change / Ospec-Task), advisory by default
// ---------------------------------------------------------------------------

const { checkTraceabilityTrailers } = require("./commit-msg-hook.js");

test("trailers: no active change → not-applicable (ok)", () => {
  const r = checkTraceabilityTrailers("feat: x\n\nbody", null);
  assert.equal(r.status, "ok");
});

test("trailers: active change + matching trailers → ok", () => {
  const msg = "feat: x\n\nbody\n\nOspec-Change: my-change\nOspec-Task: 1.2, 2.1\n";
  const r = checkTraceabilityTrailers(msg, "my-change");
  assert.equal(r.status, "ok");
});

test("trailers: active change + missing trailer → missing", () => {
  const r = checkTraceabilityTrailers("feat: x\n\nbody", "my-change");
  assert.equal(r.status, "missing");
});

test("trailers: trailer names a different change → mismatch with both names in detail", () => {
  const msg = "feat: x\n\nOspec-Change: other-change\nOspec-Task: 1.1\n";
  const r = checkTraceabilityTrailers(msg, "my-change");
  assert.equal(r.status, "mismatch");
  assert.match(r.detail, /other-change/);
  assert.match(r.detail, /my-change/);
});

test("trailers: Ospec-Change present without Ospec-Task → missing-task", () => {
  const msg = "feat: x\n\nOspec-Change: my-change\n";
  const r = checkTraceabilityTrailers(msg, "my-change");
  assert.equal(r.status, "missing-task");
});

test("trailers: merge/revert/fixup commits are exempt", () => {
  for (const subject of ["Merge branch 'x'", "Revert \"feat: x\"", "fixup! feat: x"]) {
    const r = checkTraceabilityTrailers(subject, "my-change");
    assert.equal(r.status, "ok", subject);
  }
});
